---
- name: Test SSH connectivity on MikroTik
  hosts: mikrotik
  gather_facts: no
  connection: network_cli
  tasks:
    - name: Check uptime
      community.routeros.command:
        commands:
          - /routing ospf neighbor print
          - /ip route print
          #- ping 192.168.100.151
      register: result

    - name: Print result
      debug:
        var: result
